#!/usr/bin/env bash
# lib/report.sh — generate report.md and merged findings.json from triage output

generate_report() {
  local target="$1"
  local outdir="$2"

  if [ ! -s "$outdir/findings.json" ]; then
    log_warn "findings.json empty — writing no-findings report"
    _write_empty_report "$target" "$outdir"
    return
  fi

  log_info "Generating report..."

  python3 - "$outdir" "$target" << 'PYEOF'
import json, os, sys
from pathlib import Path
from datetime import datetime

outdir  = sys.argv[1]
target  = sys.argv[2]
now     = datetime.now().strftime("%Y-%m-%d %H:%M")

findings_path  = Path(outdir) / "findings.json"
triage_path    = Path(outdir) / "ai_triage.json"
report_path    = Path(outdir) / "report.md"

findings = json.loads(findings_path.read_text())
triage   = []
if triage_path.exists() and triage_path.stat().st_size > 0:
    try:
        triage = json.loads(triage_path.read_text())
    except json.JSONDecodeError:
        pass

# Merge triage fields into findings by id
tmap = {t["id"]: t for t in triage}
for f in findings:
    t = tmap.get(f["id"], {})
    f["is_real"]       = t.get("is_real")
    f["ai_confidence"] = t.get("ai_confidence")
    f["ai_reason"]     = t.get("ai_reason")
    f["chain_id"]      = t.get("chain_id")
    f["cvss_score"]    = t.get("cvss_score")
    f["cvss_vector"]   = t.get("cvss_vector")

# Write merged findings.json
findings_path.write_text(json.dumps(findings, indent=2))

# ── Count by severity ─────────────────────────────────────────────────────────
from collections import Counter, defaultdict
counts = Counter(f["severity"] for f in findings)
real_counts = Counter(
    f["severity"] for f in findings if f.get("is_real") is True
)

# ── Build chains map ──────────────────────────────────────────────────────────
chains = defaultdict(list)
for f in findings:
    if f.get("chain_id") is not None:
        chains[f["chain_id"]].append(f)

# ── Severity emoji ────────────────────────────────────────────────────────────
sev_icon = {
    "critical": "🔴", "high": "🟠", "medium": "🟡",
    "low": "🟢", "info": "⚪"
}

lines = []
lines.append(f"# BugHawk Security Report")
lines.append(f"")
lines.append(f"**Target:** {target}  ")
lines.append(f"**Scan Date:** {now}  ")
lines.append(f"**Report:** Auto-generated by BugHawk")
lines.append(f"")
lines.append(f"---")
lines.append(f"")

# ── Summary table ─────────────────────────────────────────────────────────────
lines.append(f"## Summary")
lines.append(f"")
lines.append(f"| Severity | Total Found | AI Confirmed |")
lines.append(f"|----------|------------|--------------|")
for sev in ["critical", "high", "medium", "low", "info"]:
    icon = sev_icon.get(sev, "")
    total = counts.get(sev, 0)
    real  = real_counts.get(sev, 0)
    if total:
        lines.append(f"| {icon} {sev.capitalize()} | {total} | {real} |")
lines.append(f"")

# ── Exploit chains section ────────────────────────────────────────────────────
if chains:
    lines.append(f"## Exploit Chains")
    lines.append(f"")
    for chain_id, chain_findings in chains.items():
        chain_file = Path(outdir) / f"chain_{chain_id}.json"
        chain_title = f"Chain #{chain_id}"
        chain_severity = "high"
        attack_steps = []
        combined_impact = ""
        chain_cvss = ""

        if chain_file.exists():
            try:
                cd = json.loads(chain_file.read_text())
                chain_title    = cd.get("chain_title", chain_title)
                chain_severity = cd.get("chain_severity", chain_severity)
                attack_steps   = cd.get("attack_steps", [])
                combined_impact= cd.get("combined_impact", "")
                chain_cvss     = cd.get("cvss_score", "")
            except json.JSONDecodeError:
                pass

        icon = sev_icon.get(chain_severity, "🔴")
        lines.append(f"### {icon} {chain_title}")
        lines.append(f"**Severity:** {chain_severity.capitalize()}  ")
        if chain_cvss:
            lines.append(f"**CVSS:** {chain_cvss}  ")
        lines.append(f"")

        if attack_steps:
            lines.append(f"**Attack Steps:**")
            for i, step in enumerate(attack_steps, 1):
                lines.append(f"{i}. {step}")
            lines.append(f"")

        if combined_impact:
            lines.append(f"**Impact:** {combined_impact}")
            lines.append(f"")

        lines.append(f"**Findings in chain:**")
        for f in chain_findings:
            lines.append(f"- [{f['severity'].upper()}] {f['type']} — {f['url']}")
        lines.append(f"")

    lines.append(f"---")
    lines.append(f"")

# ── Per-finding sections ──────────────────────────────────────────────────────
lines.append(f"## Findings")
lines.append(f"")

sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
sorted_findings = sorted(findings, key=lambda f: sev_order.get(f.get("severity","info"), 5))

for f in sorted_findings:
    sev  = f.get("severity", "info")
    icon = sev_icon.get(sev, "⚪")
    fid  = f.get("id", "?")
    ftype= f.get("type", "unknown")
    url  = f.get("url", "")
    tool = f.get("tool", "")

    # Confidence badge
    conf = f.get("ai_confidence")
    try:
        conf_str = f" *(AI confidence: {float(conf):.0%})*" if conf is not None else ""
    except (TypeError, ValueError):
        conf_str = ""
    is_real = f.get("is_real")
    status_str = ""
    if is_real is True:
        status_str = " ✅"
    elif is_real is False:
        status_str = " ❌ *(likely false positive)*"

    lines.append(f"### [{fid}] {icon} {ftype.upper()}{status_str}{conf_str}")
    lines.append(f"")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| **Severity** | {sev.capitalize()} |")
    lines.append(f"| **Tool** | {tool} |")
    lines.append(f"| **URL** | `{url}` |")

    param = f.get("parameter", "")
    if param:
        lines.append(f"| **Parameter** | `{param}` |")

    cvss = f.get("cvss_score", "")
    if cvss:
        lines.append(f"| **CVSS Score** | {cvss} |")

    cvss_vec = f.get("cvss_vector", "")
    if cvss_vec:
        lines.append(f"| **CVSS Vector** | `{cvss_vec}` |")

    chain_id = f.get("chain_id")
    if chain_id is not None:
        lines.append(f"| **Chain** | #{chain_id} |")

    lines.append(f"")

    desc = f.get("description", "")
    if desc:
        lines.append(f"**Description:** {desc}")
        lines.append(f"")

    evidence = f.get("evidence", "")
    if evidence:
        lines.append(f"**Evidence:**")
        lines.append(f"```")
        lines.append(evidence[:800])
        lines.append(f"```")
        lines.append(f"")

    ai_reason = f.get("ai_reason", "")
    if ai_reason:
        lines.append(f"**AI Analysis:** {ai_reason}")
        lines.append(f"")

    lines.append(f"---")
    lines.append(f"")

report_path.write_text("\n".join(lines), encoding="utf-8")
print(f"report.md written ({len(findings)} findings)")
PYEOF

  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    log_tool_error "report" "Python script failed (exit $exit_code)"
    _write_empty_report "$target" "$outdir"
    return
  fi

  log_success "Report: $outdir/report.md"

  # Auto-open
  if [ "${OPEN_REPORT_AFTER:-true}" = "true" ] && [ -f "$outdir/report.md" ]; then
    if command -v xdg-open &>/dev/null; then
      xdg-open "$outdir/report.md" &>/dev/null &
    elif command -v open &>/dev/null; then
      open "$outdir/report.md" &>/dev/null &
    fi
  fi
}

# ── Empty report fallback ─────────────────────────────────────────────────────
_write_empty_report() {
  local target="$1" outdir="$2"
  local now
  now=$(date '+%Y-%m-%d %H:%M')
  {
    printf '# BugHawk Security Report\n\n'
    printf '**Target:** %s  \n' "$target"
    printf '**Scan Date:** %s\n\n' "$now"
    printf '---\n\n'
    printf '## Summary\n\n'
    printf 'No findings were detected across all scan modules.\n\n'
    printf 'This may indicate:\n'
    printf '- The target has strong security controls\n'
    printf '- Some tools were skipped or timed out (check errors.log)\n'
    printf '- The scan depth was set to quick mode\n\n'
    printf 'Check `errors.log` for tool failures.\n'
  } > "$outdir/report.md"
  log_info "Empty report written to $outdir/report.md"
}
